// Code Generated By 'npm run config', Please DO NOT Edit!!!!! 
        
const config = {
    appId: "cli_a6809429a339d00a", //网页应用appId
    appSecret: "zQl92ILRIHrEVjIolDCYLeXJjzN12LBM", //网页应用secret
    getUserAccessTokenPath:  "/api/get_user_access_token", //免登-获取user_access_token的api path
    getSignParametersPath:  "/api/get_sign_parameters", //鉴权-获取鉴权参数的api path
    noncestr: "xD25WjP8G4zzn8er2Cpz2WFjthmRJ3i8",   //随机字符串，用于鉴权签名用
    apiPort: "8989",   //后端指定端口
}
    
module.exports = { config : config };